openapi: 3.0.3
info:
  title: HeartAuth Core - Administrator
  version: 1.0.0
tags:
  - name: Tenants
    description: Tenant lifecycle operations
paths:
  /admin/v1/tenants:
    post:
      tags:
        - Tenants
      summary: Register a new tenant
      description: Creates a new tenant.
      operationId: registerTenant
      responses:
        '201':
          description: Tenant created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTenantResponse'
              examples:
                created:
                  value:
                    id: "a9b2f1a6-2a36-4f1f-bc3b-9d63f5a8f5a2"
                    apiKey: "a9b2f1a6-2a36-4f1f-bc3b-9d63f5a8f5a2"
  /admin/v1/model-action:
    get:
      tags:
        - ModelAction
      operationId: getModelAction
      summary: Retrieve Model API action summary
      responses:
        '200':
          description: Generic result map
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /admin/v1/ref-data-overwrite:
    post:
      tags:
        - ModelAction
      operationId: overwriteRefData
      summary: Overwrite refData (demo purpose)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefEcgOverwriteRequest'
      responses:
        '201':
          description: Command successful
components:
  schemas:
    CreateTenantResponse:
      type: object
      required:
        - id
        - apiKey
      properties:
        id:
          type: string
          format: uuid
        apiKey:
          type: string
          format: uuid
    RefEcgOverwriteRequest:
      type: object
      required:
        - tenantId
        - userId
        - refEcg
      properties:
        tenantId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        refEcg:
          type: array
          items:
            type: array
            items:
              type: number
              format: float



