openapi: 3.0.3
info:
  title: Model API
  version: 1.0.0
paths:
  /v1/predict:
    post:
      operationId: predict
      tags:
        - Prediction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PredictRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PredictResponse"
components:
  schemas:
    PredictRequest:
      type: object
      description: Flexible input payload accepted by the model.
      required:
        - refEcg
        - testEcg
      properties:
        refEcg:
          type: array
          items:
            type: array
            items:
              type: number
              format: float
        testEcg:
          type: array
          items:
            type: number
            format: float
    PredictResponse:
      type: object
      required:
        - prediction
      properties:
        prediction:
          type: boolean
        score:
          type: number
          format: float
        error:
          type: string
