openapi: 3.0.3
info:
  title: Model API
  version: 1.0.0
paths:
  /model-api:
    post:
      tags:
        - Prediction
      operationId: registerTenant
      responses:
        '201':
          description: Model Api Kafka Interface
components:
  schemas:
    PredictRequest:
      type: object
      required:
        - refEcg
        - testEcg
      properties:
        refEcg:
          type: array
          items:
            type: array
            items:
              type: number
              format: float
        testEcg:
          type: array
          items:
            type: number
            format: float
    PredictResponse:
      type: object
      required:
        - ok
      properties:
        ok:
          type: boolean
        prediction:
          type: boolean
        score:
          type: number
          format: float
        error:
          type: string
    CombinedModelAction:
      type: object
      required:
        - timestamp
        - predictResponse
        - predictRequest
      properties:
        predictRequest:
          $ref: "#/components/schemas/PredictRequest"
        predictResponse:
          $ref: "#/components/schemas/PredictResponse"
        timestamp:
          type: integer
          format: int64