openapi: 3.0.3
info:
  title: Model API
  version: 1.0.0
paths: { }
components:
  schemas:
    PredictRequest:
      type: object
      description: Flexible input payload accepted by the model.
      required:
        - refEcg
        - testEcg
      properties:
        refEcg:
          type: array
          items:
            type: array
            items:
              type: number
              format: float
        testEcg:
          type: array
          items:
            type: number
            format: float
    PredictResponse:
      type: object
      required:
        - prediction
      properties:
        prediction:
          type: boolean
        score:
          type: number
          format: float
