openapi: 3.0.3
info:
  title: ECG Orchestrator API — Shared Components
  version: 1.0.0
components:
  parameters:
    JtiParam:
      name: jti
      in: path
      required: true
      schema:
        type: string
        format: uuid
    ChallengeIdParam:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    PairingInitRequest:
      type: object
      required:
        - deviceId
        - displayName
        - publicKeyPem
        - fcmToken
        - platform
      properties:
        deviceId:
          type: string
        displayName:
          type: string
        publicKeyPem:
          type: string
        fcmToken:
          type: string
        platform:
          $ref: '#/components/schemas/Platform'
        osVersion:
          type: string
        model:
          type: string
        attestation:
          $ref: '#/components/schemas/Attestation'
    PairingInitResponse:
      type: object
      required:
        - nonce
      properties:
        nonce:
          type: string
    PairingConfirmRequest:
      type: object
      required:
        - dataToken
        - deviceId
        - signature
        - alg
      properties:
        dataToken:
          type: string
          description: |
            JWT encrypted with ecgData
        deviceId:
          type: string
        signature:
          type: string
        alg:
          $ref: '#/components/schemas/EncryptionAlgo'
    DeviceInfo:
      type: object
      required:
        - deviceId
        - displayName
        - publicKeyPem
        - fcmToken
        - createdAt
      properties:
        deviceId:
          type: string
        displayName:
          type: string
        publicKeyPem:
          type: string
        fcmToken:
          type: string
        attestation:
          $ref: '#/components/schemas/Attestation'
        createdAt:
          type: integer
          format: int64
    Attestation:
      type: object
      properties:
        type:
          type: string
          enum:
            - play-integrity
            - safety-net
            - devicecheck
            - none
        verdict:
          type: string
        payload:
          type: object
          additionalProperties: true
    ChallengeCreateRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid
        ttlSeconds:
          type: integer
          minimum: 30
          maximum: 300
          default: 120
    ChallengeCreateResponse:
      type: object
      required:
        - challengeId
      properties:
        challengeId:
          type: string
          format: uuid
    ChallengeCompleteRequest:
      type: object
      required:
        - dataToken
        - signature
      properties:
        dataToken:
          type: string
          description: |
            JWT encrypted with ecgData
        signature:
          type: string
          description:  |
            Signed nonce
    PairingCreateRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid
        ttlSeconds:
          type: integer
          minimum: 30
          maximum: 300
          default: 120
    PairingCreateResponse:
      type: object
      required:
        - jti
        - jwt
      properties:
        jti:
          type: string
          format: uuid
        jwt:
          type: string
    StatusResponse:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/FlowStatus'
        reason:
          type: string
    FlowStatus:
      type: string
      description: Lifecycle state of a challenge.
      enum:
       - CREATED
       - PENDING
       - APPROVED
       - DENIED
       - EXPIRED
       - NOT_FOUND
    Platform:
      type: string
      enum:
        - ANDROID
        - IOS
    EncryptionAlgo:
      type: string
      enum:
        - ES256
    JwkSet:
      type: object
      required: [keys]
      properties:
        keys:
          type: array
          items:
            $ref: '#/components/schemas/ECJwk'
    ECJwk:
      type: object
      required: [kty, crv, x, y]
      properties:
        kty:
          type: string
          enum: [EC]
        crv:
          type: string
          enum: [P-256, P-384, P-521]
        x:
          type: string
          pattern: '^[A-Za-z0-9_-]+$'
        y:
          type: string
          pattern: '^[A-Za-z0-9_-]+$'
        kid: { type: string }
        use: { type: string, enum: [sig, enc] }
        alg: { type: string }
        x5u: { type: string, format: uri }
        x5c: { type: array, items: { type: string } }
        x5t: { type: string }
        "x5t#S256": { type: string }

