openapi: 3.0.3
info:
  title: ECG Orchestrator API — External
  version: 1.0.0
  description: Endpoints called by the mobile app.
tags:
  - name: Pairing
    description: Device enrollment from the mobile app.
  - name: Challenge
    description: Completing login-time challenges from the device.
  - name: Health
    description: Administrative endpoints.
paths:
  /.well-known/jwks.json:
    get:
      tags: [WellKnown]
      summary: Get JSON Web Key Set (JWKS)
      operationId: getJwks
      security: []
      responses:
        '200':
          description: JWKS document
          content:
            application/json:
              schema: { $ref: './components.yml#/components/schemas/JwkSet' }
  /actuator/health:
    get:
      tags:
        - Health
      summary: Get overall application health
      description: Returns the aggregated health status of the application.
      operationId: getHealth
      responses:
        '200':
          description: Application is healthy
  /external/v1/pair/exchange/init:
    post:
      operationId: externalPairingInit
      tags:
        - Pairing
      summary: Begin device pairing using a one-time pairing JWT from Keycloak.
      description: |
        Mobile app calls this after scanning the QR on the Keycloak Required Action page.
        Returns a fresh nonce and creates pairing state keyed by JWT `jti`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/PairingInitRequest'
      responses:
        '201':
          description: Pairing initiated; device must confirm proof-of-possession.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/PairingInitResponse'
  /external/v1/pair/exchange/confirm:
    post:
      operationId: externalPairingConfirm
      tags:
        - Pairing
      summary: Confirm device pairing by proving possession of the generated private key.
      description: |
        Device signs the server-provided nonce (and context) with its hardware-backed
        private key. On success, orchestrator persists device metadata and marks `jti` as linked.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/PairingConfirmRequest'
      responses:
        '204':
          description: Pairing outcome recorded.

  /external/v1/challenge/{id}/complete:
    post:
      operationId: externalChallengeComplete
      tags:
        - Challenge
      summary: Complete a challenge from the device after ECG pass and signature verification.
      description: |
        Mobile app posts a signed assertion proving possession of the device key.
        Server validates signature (using stored public key), nonce, and policy.
      parameters:
        - $ref: './components.yml#/components/parameters/ChallengeIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/ChallengeCompleteRequest'
      responses:
          '204':
            description: Challenge outcome recorded.
