openapi: 3.0.3
info:
  title: ECG Orchestrator API — Internal
  version: 1.0.0
  description: Endpoints called by Keycloak/server.

tags:
  - name: Pairing
    description: Status/polling for pairing.
  - name: Challenge
    description: Creating and polling challenges.

paths:
  /internal/v1/pair/status/{jti}:
    get:
      operationId: internalPairingStatus
      tags: [ Pairing ]
      summary: Poll current pairing status.
      description: |
        Keycloak Required Action (or app-side page) checks if the device has been linked.
        May be unauthenticated if `jti` is unguessable; optionally bind to `X-KC-Session`.
      parameters:
        - $ref: './components.yml#/components/parameters/JtiParam'
        - in: header
          name: X-KC-Session
          required: false
          schema: { type: string }
          description: Optional binding to Keycloak `authSessionId`.
      responses:
        '200':
          description: Current state of the pairing operation.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/PairingStatusResponse'
              examples:
                pending: { value: { state: pending } }
                linked:  { value: { state: linked } }
                expired: { value: { state: expired } }

  /internal/v1/challenge:
    post:
      operationId: internalChallengeCreate
      tags: [ Challenge ]
      summary: Create a login-time ECG challenge and deliver FCM push.
      description: |
        Called by the Keycloak Authenticator. Creates a short-lived challenge, selects a target
        device, sends an FCM data message, and returns challenge metadata.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/ChallengeCreateRequest'
            examples:
              create:
                value:
                  userId: "1a2b3c-user"
                  deviceId: "android:3f24a1c2"
                  ttlSeconds: 120
      responses:
        '201':
          description: Challenge created and push dispatched.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/ChallengeCreateResponse'
              examples:
                ok:
                  value:
                    challengeId: "79f1a833-2a0c-4af9-9d8a-8ff8121c98b2"
                    deviceId: "android:3f24a1c2"
                    nonce: "vxxP3w5F0Z4J9eN9oVY2BA=="
                    exp: 1723712460

  /internal/v1/challenge/{id}/status:
    get:
      operationId: internalChallengeStatus
      tags: [ Challenge ]
      summary: Poll challenge status.
      description: |
        Used by the Keycloak login page to display live progress. Can be open if `id` is unguessable;
        alternatively bind to `X-KC-Session`.
      parameters:
        - $ref: './components.yml#/components/parameters/ChallengeIdParam'
        - in: header
          name: X-KC-Session
          required: false
          schema: { type: string }
          description: Optional binding to Keycloak `authSessionId`.
      responses:
        '200':
          description: Current state of the challenge.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/ChallengeStatusResponse'
              examples:
                pending:  { value: { state: pending } }
                approved: { value: { state: approved } }
                denied:   { value: { state: denied, reason: user_cancelled } }
                expired:  { value: { state: expired } }
