openapi: 3.0.3
info:
  title: ECG Orchestrator API — Internal
  version: 1.0.0
  description: Endpoints called by Keycloak/server.

tags:
  - name: Pairing
    description: Status/polling for pairing.
  - name: Challenge
    description: Creating and polling challenges.

paths:
  /internal/v1/pair/status/{jti}:
    get:
      operationId: internalPairingStatus
      tags:
        - Pairing
      summary: Poll current pairing status.
      description: |
        Keycloak Required Action (or app-side page) checks if the device has been linked.
        May be unauthenticated if `jti` is unguessable; optionally bind to `X-KC-Session`.
      parameters:
        - $ref: './components.yml#/components/parameters/JtiParam'
        - in: header
          name: X-KC-Session
          required: false
          schema:
            type: string
          description: Optional binding to Keycloak `authSessionId`.
      responses:
        '200':
          description: Current state of the pairing operation.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/StatusResponse'
  /internal/v1/challenge:
    post:
      operationId: internalChallengeCreate
      tags:
        - Challenge
      summary: Create a login-time ECG challenge and deliver FCM push.
      description: |
        Called by the Keycloak Authenticator. Creates a short-lived challenge, selects a target
        device, sends an FCM data message, and returns challenge metadata.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/ChallengeCreateRequest'
      responses:
        '201':
          description: Challenge created and push dispatched.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/ChallengeCreateResponse'
  /internal/v1/challenge/{id}/status:
    get:
      operationId: internalChallengeStatus
      tags:
        - Challenge
      summary: Poll challenge status.
      description: |
        Used by the Keycloak login page to display live progress. Can be open if `id` is unguessable;
        alternatively bind to `X-KC-Session`.
      parameters:
        - $ref: './components.yml#/components/parameters/ChallengeIdParam'
        - in: header
          name: X-KC-Session
          required: false
          schema:
            type: string
          description: Optional binding to Keycloak `authSessionId`.
      responses:
        '200':
          description: Current state of the challenge.
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/StatusResponse'
  /internal/v1/pair:
    post:
      operationId: internalPairingCreate
      tags:
        - Pairing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/PairingCreateRequest'
      responses:
        '201':
          description: Pairing token minted
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/PairingCreateResponse'