openapi: 3.0.3
info:
  title: Model API
  version: 1.0.0
paths:
  /predict:
    post:
      operationId: predict
      tags: [Prediction]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictResponse'
components:
  schemas:
    In:
      type: object
      additionalProperties: true
      description: Flexible input payload accepted by the model.
      properties:
        anything:
          type: string

    PredictResponse:
      type: object
      required: [prediction]
      properties:
        prediction:
          type: boolean
